-- ============================================================================
-- ADD TOPIC COLUMN TO POSTS
-- ============================================================================
-- 
-- Migration to add topic categorization to posts.
-- Topic is selected from a predefined list and can be auto-generated by AI.
--
-- Run this in your Supabase SQL Editor to update the database.
-- ============================================================================

-- Add topic column to posts table
ALTER TABLE public.posts 
ADD COLUMN IF NOT EXISTS topic TEXT;

-- Add an index for filtering posts by topic
CREATE INDEX IF NOT EXISTS posts_topic_idx ON public.posts(topic) WHERE topic IS NOT NULL;

-- Comment for documentation
COMMENT ON COLUMN public.posts.topic IS 'Post topic/category selected from predefined list';
